version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./auto-southwest-check-in:/app/auto-southwest-check-in

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
